// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool to work around XAML compiler issues
//      with .NET 11 and Windows App SDK 1.7 in Release mode.
//
//      与 XamlCompiler 自动生成的 App.g.cs / App.g.i.cs 互补：
//      - csproj 对 Windows Release TFM 定义了 DISABLE_XAML_GENERATED_MAIN，
//        自动生成的 Program 部分会被跳过，由本文件的 Program 提供（入口点兜底）。
//      - Debug 模式下 XamlCompiler 正常生成代码，本文件由 csproj 排除（Compile Remove），
//        避免 CS0111 重复成员。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CatClawVideo.Maui.WinUI
{
#if DISABLE_XAML_GENERATED_MAIN
    /// <summary>
    /// Program class
    /// </summary>
    public static class Program
    {
        [global::System.STAThreadAttribute]
        static void Main(string[] args)
        {
            global::WinRT.ComWrappersSupport.InitializeComWrappers();
            global::Microsoft.UI.Xaml.Application.Start((p) => {
                var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
                global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
                new App();
            });
        }
    }
#endif
}
